name: life_academy
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - plotly
  - pandas
  - ipywidgets
  - jupyter_contrib_nbextensions
  - glpk
  - matplotlib
  - tqdm
  - pip:
    - git+https://github.com/OSeMOSYS/otoole.git@develop#egg=otoole

